[package]
name = "grapevine"
version = "0.1.3"
description = "A simple peer-to-peer gossip protocol handler"
authors = ["Kobby Pentangeli <kobbypentangeli@gmail.com>"]
repository = "https://github.com/kobby-pentangeli/grapevine"
documentation = "https://docs.rs/grapevine"
license = "MIT or APACHE-2.0"
readme = "README.md"
keywords = ["p2p", "peer-to-peer", "gossip"]
categories = ["network-programming"]
edition = "2021"

[dependencies]
bincode = "1.3.3"
clap = "4.1.1"
hhmmss = "0.1.0"
log = "0.4.17"
message-io = "0.11.1"
petname = "1.1.3"
serde = { version = "1", features = ["derive"] }
thiserror = "1.0.38"
