[package]
name = "grapevine"
version = "0.1.0"
description = "Peer-to-peer gossip protocol handler"
authors = ["Kobby Pentangeli <kobbypentangeli@gmail.com>"]
repository = "https://github.com/kobby-pentangeli/grapevine"
readme = "README.md"
keywords = ["p2p", "peer-to-peer", "gossip"]
categories = ["network programming"]
edition = "2021"

[dependencies]
clap = "2.33.3"
bincode = "1.3.2"
hhmmss = "0.1.0"
log = "0.4.14"
message-io = "0.11.1"
petname = "1.1.0"
serde = "1.0.125"
